name: Java CI - Build and Upload JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build project with Maven
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-java-app-jar
        path: target/*.jar
